BlogBravo/Controllers/BrowseController.cs
using BlogBravo.Data;
using BlogBravo.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogBravo.Controllers
{
    public class BrowseController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        public BrowseController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Browse
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ViewBlogs()
        {
            List<Blog> Blogs = _context.Blogs.ToList();

            return View(Blogs);
        }

        public ActionResult ViewPosts()
        {
            List<Post> Posts = _context.Posts.OrderBy(p => p.Title).OrderByDescending(p=>p.Views).Take(10).ToList();
            return View(Posts);
        }

        public ActionResult ViewTags()
        {
            List<Tag> Tags = _context.Tags.Include(t => t.Post).ToList();
            Tags = Tags.OrderByDescending(t => t.Post.Count).ToList();

            return View(Tags);
        }

        public ActionResult ViewPostsWithTag()
        {
            string path = HttpContext.Request.Path;
            string[] pathComponents = path.Split('/');
            int tagId = Convert.ToInt32(pathComponents[pathComponents.Length - 1]);
            List<Post> postsThatUsesTheTag = new List<Post>();

            if (tagId > 0)
            {
                List<Post> Posts = _context.Posts.Include(p => p.Tag).ToList();

                if (Posts.Count != 0 )
                {
                    foreach(Post post in Posts)
                    {
                        if (post.Tag.Count > 0)
                        {
                            foreach (Tag tag in post.Tag)
                            {
                                if (tag.Id == tagId)
                                {
                                    postsThatUsesTheTag.Add(post);
                                }
                            }
                        }
                    }
                }

                return View(postsThatUsesTheTag);
            }

            return View();
        }

        public ActionResult ViewPost()
        {
            string path = HttpContext.Request.Path;
            string[] pathComponents = path.Split('/');
            int postId = Convert.ToInt32(pathComponents[pathComponents.Length - 1]);

            if (postId > 0)
            {
                var Post = _context.Posts.Include(p => p.Comment).FirstOrDefault(p => p.Id == postId);
                Post = _context.Posts.Include(p => p.Tag).FirstOrDefault(p => p.Id == postId);
                var comments = _context.Comments.Include(c => c.Author).Where(c => c.PostId == postId);
                ViewBag.Comments = comments;

                return View(Post);
            }

            return View();
        }

        public ActionResult Views()
        {
            string path = HttpContext.Request.Path;
            string[] pathComponents = path.Split('/');
            int BlogId = Convert.ToInt32(pathComponents[pathComponents.Length - 1]);

            if (BlogId > 0)
            {
                Blog blog = _context.Blogs.Find(BlogId);
                var Posts = _context.Posts.Include(p => p.Comment).Where(p => p.BlogId == BlogId).OrderByDescending(p => p.Created);
                foreach (var post in Posts)
                {
                    if (post.Comment.Count != 0)
                    {
                        var comments = _context.Comments.Include(c => c.Author).Where(c => c.PostId == post.Id).ToList();
                        post.Comment = comments;
                    }
                }

                // Increase post views

                foreach (var post in Posts)
                {
                    Post postToUpdate = _context.Posts.Find(post.Id);
                    post.Views++;

                    postToUpdate.Views = post.Views;
                    _context.Update(postToUpdate);
                }

                _context.SaveChanges();

                // Pass all posts as a ViewBag

                ViewBag.BlogPosts = Posts;

                string[] postDates = new string [Posts.Count()];

                int i = 0;
                foreach(var post in Posts)
                {
                    if (post != null)
                    {
                        postDates[i] = post.Created.ToString("yyyy-MMMM-dd");
                        i++;
                    }
                }

                Array.Sort(postDates);

                List<string> years = new List<string>();
                List<string> months = new List<string>();
                string[] componentsOfpostDates = new string[3];

                foreach (string postDate in postDates)
                {
                    componentsOfpostDates = postDate.Split('-');
                    years.Add(componentsOfpostDates[0]);
                }

                ViewBag.postYears = years = years.OrderBy(y => y.ElementAt(0)).Distinct().ToList();
                foreach(var year in years)
                {
                    for (i = 0; i < postDates.Length; i++)
                    {
                        componentsOfpostDates = postDates[i].Split('-');
                        if (String.Equals(year, componentsOfpostDates[0]))
                        {
                            months.Add(componentsOfpostDates[1]);
                        }
                    }

                    TempData[year] = months.OrderBy(m => m.ElementAt(0)).Distinct().ToList();
                    months.Clear();
                }
                
                return View(blog);
            }

            return View();
        }

            public ActionResult ViewBlogPost()
        {
             string path = HttpContext.Request.Path;
            string[] pathComponents = path.Split('/');
            int BlogId = Convert.ToInt32(pathComponents[pathComponents.Length - 1]);

            if (BlogId > 0)
            {
                var Post = _context.Posts.Where(p => p.BlogId == BlogId);
                var blog = _context.Blogs.Find(BlogId);
                ViewBag.BlogName = blog.Title;  
                return View(Post);
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddComment(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            string url = Request.Form["url"];

            string commentUserName = Request.Form["post-comment-user"];

            var post = await _context.Posts.Include(p => p.Comment).FirstOrDefaultAsync(p => p.Id == id);


            if (post == null)
            {
                return NotFound();
            }
            else
            {
                post.Comment.Add(new Comment
                {
                    Created = DateTime.Now,
                    Body = Request.Form["post-comment-body"],
                    Author = await _userManager.GetUserAsync(HttpContext.User)
                });

                _context.Update(post);
                await _context.SaveChangesAsync();
            }

            ViewBag.Comments = post.Comment;

            return Redirect(url);
        }
    }
}

BlogBravo/Controllers/SearchController.cs
using BlogBravo.Data;
using BlogBravo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogBravo.Controllers
{
    public class SearchController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;

        public SearchController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }


        public ActionResult Index(string query)
        {
            var ApplicationDbContext = _context;
            SearchVM search = new SearchVM();

            search.BlogList = _context.Blogs.ToList();
            search.PostList = _context.Posts.Include(p=>p.Blog).ToList();
            search.TagList = _context.Tags.Include(t => t.Post).ToList();

            ViewBag.Query = query;
            TempData["searchpath"] = "search";
            TempData["query"] = query;
            if (!String.IsNullOrEmpty(query))
            {
                search.BlogList = search.BlogList.Where(b => b.Title.ToUpper().Contains(query.ToUpper())).ToList();
                search.PostList = search.PostList.Where(p => p.Title.ToUpper().Contains(query.ToUpper())).ToList();
                search.TagList = search.TagList.Where(t => t.Name.ToUpper().Contains(query.ToUpper())).ToList();
                return View(search);
            }
            else
            { 
                return Problem("The query string was empty!"); 
            }


        }

        public ActionResult ViewBlog(int? blogId, string query)
        {
            SearchVM search = new SearchVM();

            if (blogId != null)
            {
                Blog blog = _context.Blogs.Find(blogId);
                ViewBag.Blog = blog;
                search.PostList = new List<Post>();

               Post postWithTheLatestDate = _context.Posts.Where(p => p.BlogId == blog.Id).OrderByDescending(p => p.Created).FirstOrDefault();
               var PostList = _context.Posts.Where(p => p.BlogId == blog.Id).OrderByDescending(p => p.Created).AsEnumerable().GroupBy(p =>p.Created).Select(g=>g.First());

                foreach (var post in PostList)
                {
                    if(post.Created.ToString("MM").Equals(postWithTheLatestDate.Created.ToString("MM")))
                    { 
                        search.PostList.Add(post); 
                    }
                    
                }

                return View(search.PostList);
            }
            else
            {
                return Problem("Could not retrieve the posts with specific dates");
            }
        }

        public ActionResult ViewPost(int? postId)
        {
            SearchVM search = new SearchVM();

            if (postId != null)
            {
                Post post = _context.Posts.Find(postId);
                Blog blog = _context.Blogs.Find(post.BlogId);
                ViewBag.Blog = blog;
                search.PostList = new List<Post>();
                search.PostList = _context.Posts.
                                     Where(p => p.BlogId == blog.Id)
                                    .ToList();

                search.PostList = search.PostList.Where(p => p.Created.ToString("MM").Equals(post.Created.ToString("MM"))).ToList();

                return View(search.PostList);
            }
            else
            {
                return Problem("Could not retrieve the posts with specific dates");
            }
        }

        public ActionResult ViewPostById(int? postId)
        {
            return View();
        }


    }
}

BlogBravo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogBravo</title>
    <script src="https://kit.fontawesome.com/64e875fda5.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Vujahday+Script&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@200&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;1,100;1,200;1,300;1,400;1,500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/blogbravo.css" />
</head>
<body>
    <partial name="_Spinner" />
    @using Microsoft.AspNetCore.Identity
    @using BlogBravo.Data
    @inject SignInManager<ApplicationUser> SignInManager
    @inject UserManager<ApplicationUser> UserManager
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow py-0">
            <div id ="nav-div" class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="font-family: 'Edwardian Script ITC'; font-size: 3rem;">Blog Bravo&ensp;<i title="Blog Bravo Home" class="fas fa-home mr-5" style="font-size:2rem;"></i></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white mr-2" asp-area="" asp-controller="Browse" asp-action="Index"><i class="fab fa-blogger mr-5" data-toggle="tooltip" data-placement="bottom" title="Blog Bravo Browse" style="font-size:2rem;"></i></a>
                        </li>
                        <li>
                            <form method="get" name="Searchform" class="form-inline" asp-controller="Search" asp-action="Index">
                                <div class="input-group mt-1">
                                    <input id="search" type="search" placeholder="Search..." name="query" class="form-control border border-right-0 border-dark" style="border-top-left-radius:25px; border-bottom-left-radius:25px;">

                                    <div class="input-group-append">
                                        <span id="search-btn" class="btn btn-outline-dark border-left-0 bg-white" style="border-top-right-radius: 25px; border-bottom-right-radius: 25px;"><i class="text-black fas fa-search" onclick="Searchform.submit()"></i></span>
                                    </div>
                                </div>
                            </form>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark text-white" style="font-size:1rem;">
        <div class="container">
            &copy; @DateTime.Now.Year - Blog Bravo <i class="fab fa-linkedin"></i> <i class="fab fa-twitter-square"></i> <i class="fab fa-facebook-square"></i> - <a class="text-info" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy Policy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>

        function SetNavBarClass() {
            // Get width and height of the window excluding scrollbars
            var width = document.documentElement.clientWidth;

            if (width >= 1400) { //xxl Screen
                $(".navbar *").css("font-size", 24);
                $("#search").css("font-size", 16);
                $("#search-btn").css("font-size", 14);
                $(".fa-search").css("font-size", 14);
            }
            else if (width >= 1200 && width < 1400) { // XL Screen
                $(".navbar *").css("font-size", 24);
                 $("#search").css("font-size", 16);
                $("#search-btn").css("font-size", 14);
                $(".fa-search").css("font-size", 14);
            }
            else if (width >= 992 && width < 1200) { // Large Screen
                $(".navbar *").css("font-size", 20);
                $("#search").css("font-size", 16);
                $("#search-btn").css("font-size", 14);
                $(".fa-search").css("font-size", 14);
            }
            else if (width >= 768 && width < 992) { // Medium Screen
                $(".navbar *").css("font-size", 16);
                $("#search").css("font-size", 12);
                $("#search-btn").css("font-size", 10);
                $(".fa-search").css("font-size", 10);
            }
            else if (width >= 576 && width < 768) { // small screen
                $(".navbar *").css("font-size", 13);
                $("#search").css("font-size", 10);
                $("#search-btn").css("font-size", 8);
                $(".fa-search").css("font-size", 8);
            }
            else if (width < 576) { // X Small Screen
                $(".navbar *").css("font-size", 10);
            }
        }
        
        window.addEventListener("resize", SetNavBarClass);
        SetNavBarClass();
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BlogBravo/Views/Shared/_Spinner.cshtml
@{
    Layout = null;
}

<style>

    .loader {
        border: 16px solid #f3f3f3;
        border-radius: 50%;
        border-top: 16px solid #3498db;
        width: 120px;
        height: 120px;
        -webkit-animation: spin 2s linear infinite; /* Safari */
        animation: spin 2s linear infinite;
    }

    @@keyframes spin {
        0% {
            transform: rotate(0deg);
        }

        100% {
            transform: rotate(360deg);
        }
    }
</style>

<div id="loader"></div>