BlogBravo/Controllers/PostController.cs
using BlogBravo.Areas.Identity.Pages.Account;
using BlogBravo.Data;
using BlogBravo.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogBravo.Controllers
{
    [Authorize(Roles = "author")]
    public class PostController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<RegisterModel> _logger;
        private readonly IEmailSender _emailSender;

        public PostController(
            ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            ILogger<RegisterModel> logger,
            IEmailSender emailSender)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _emailSender = emailSender;
        }

        // GET: Post
        public async Task<IActionResult> Index(int? blogId)
        {
            ApplicationUser author = await _userManager.GetUserAsync(HttpContext.User);
            List<Post> userPosts = new List<Post>();


            if (blogId == null)
            {
                ViewBag.UserName = author.FirstName+ " " + author.LastName + "'s";
                var userBlogs = _context.Blogs.Where(b => b.Author == author);
                ViewBag.UserBlogs = userBlogs;

                foreach (var userBlog in userBlogs)
                {
                    List<Post> tempPost = _context.Posts.Where(p => p.BlogId == userBlog.Id).ToList();
                    userPosts.AddRange(tempPost);
                }
                return View(userPosts);
            }
            else
            {
                ViewBag.BlogId = blogId;
                var blog = _context.Blogs.Find(blogId);
                ViewBag.BlogName = blog.Title;
                var blogPosts = _context.Posts.Where(p => p.BlogId == blogId).ToList();

                return View(blogPosts);
            }
        }
        
        [AllowAnonymous]
        // GET: Post/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                if (!String.IsNullOrEmpty(Request.Form["postId"]))
                {
                    id = Convert.ToInt32(Request.Form["postId"]);
                }
                else
                {
                    return NotFound();
                }
            }

            if (TempData["searchpath"] != null)
            {
                TempData["searchpath"] = "search";
            }
            else
            {
                TempData["searchpath"] = null;
            }

            Post post = await _context.Posts.Include(p=>p.Comment).FirstOrDefaultAsync(p=>p.Id == id);
            post = await _context.Posts.Include(p => p.Tag).FirstOrDefaultAsync(p => p.Id == id);
            var comments =  _context.Comments.Include(c => c.Author).Where(c => c.PostId == id);

            ViewBag.Comments = comments;

            Blog blog = _context.Blogs.Find(post.BlogId);
            ApplicationUser author = await _userManager.FindByIdAsync(blog.AuthorId);
            ViewBag.blogAuthor = author.UserName;

            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        [HttpPost]
        [NonAction]
        public async Task<IActionResult> AddComment(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //string blogId = Request.Form["blog-id"];
            string commentUserName = Request.Form["post-comment-user"];

            var post = await _context.Posts.Include(p => p.Comment).FirstOrDefaultAsync(p => p.Id == id);


            if (post == null)
            {
                return NotFound();
            }
            else
            {
                post.Comment.Add(new Comment
                {
                    Created = DateTime.Now,
                    Body = Request.Form["post-comment-body"],
                    Author = await _userManager.GetUserAsync(HttpContext.User)
                });

                _context.Update(post);
                await _context.SaveChangesAsync();
            }

            ViewBag.Comments = post.Comment;

            return Redirect("/Post/Details/"+id);
        }

        // GET: Post/Create
        [Route("/Post/Create/{id}")]
        public IActionResult Create(int blogId)
        {

            string path = HttpContext.Request.Path.ToString();
            string[] pathComponent = path.Split('/');

            ViewBag.CreateBlogId = pathComponent[pathComponent.Length-1];
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePost(Post post)
        {
            Tag tag = new Tag();
            string[] tags = new string[5]; // Max 5 tags
            string none = "none";
            bool tagAlreadyExist = false;

            if (ModelState.IsValid)
            {
                tags[0] = Request.Form["first-tag"];
                tags[1] = Request.Form["second-tag"];
                tags[2] = Request.Form["third-tag"];
                tags[3] = Request.Form["fourth-tag"];
                tags[4] = Request.Form["fifth-tag"];

                foreach (string tagStr in tags)
                {
                    if (tagStr != none)
                    {
                        // Check for duplicate Tags
                        List<Tag> tagList = _context.Tags.Where(t => t.Name == tagStr).ToList();

                        if (tagList.Count > 0)
                        {
                            foreach (Tag tagItem in tagList)
                            {
                                if (String.Equals(tagItem.Name.ToUpper(), tagStr.ToUpper()))
                                {
                                    tagAlreadyExist = true;
                                    tag = tagItem;
                                    break;
                                }

                            }
                        }
                        else
                        {
                            tagAlreadyExist = false;
                        }

                        if (!tagAlreadyExist)
                        {
                            post.Tag.Add(new Tag() { Name = tagStr });
                        }
                        else
                        {
                            post.Tag.Add(tag);
                        }
                    }
                }
                post.Created = DateTime.Now; // Post creation date

                _context.Posts.Add(post);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Post/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var post = await _context.Posts.Include(p=> p.Tag).FirstOrDefaultAsync(p=> p.Id == id);

            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Body,Created,Views,Tag,BlogId")] Post post)
        {
            Tag tag = new Tag();
            string postTitle = post.Title;
            string postBody = post.Body;
            string[] tags = new string[5]; // Max 5 tags
            string none = "none";
            bool tagAlreadyExist = false;

            if (id != post.Id)
            {
                return NotFound();
            }
            else
            {
                // remove all tags from the  post
                post = await _context.Posts.Include(p => p.Tag).FirstOrDefaultAsync(p => p.Id == id);
                post.Tag.Clear();
            }

            if (ModelState.IsValid)
            {
                tags[0] = Request.Form["first-tag"];
                tags[1] = Request.Form["second-tag"];
                tags[2] = Request.Form["third-tag"];
                tags[3] = Request.Form["fourth-tag"];
                tags[4] = Request.Form["fifth-tag"];

                // delete all the tags from the post in the database

                foreach (string tagStr in tags)
                {
                    if (tagStr != none)
                    {
                        // Check for duplicate Tags
                        List<Tag> tagList = _context.Tags.Where(t => t.Name == tagStr).ToList();

                        if (tagList.Count > 0)
                        {
                            foreach (Tag tagItem in tagList)
                            {
                                if (String.Equals(tagItem.Name.ToUpper(), tagStr.ToUpper()))
                                {
                                    tagAlreadyExist = true;
                                    tag = tagItem;
                                    break;
                                }
                            }
                        }
                        else
                        {
                            tagAlreadyExist = false;
                        }

BlogBravo/Controllers/SearchController.cs
using BlogBravo.Data;
using BlogBravo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogBravo.Controllers
{
    public class SearchController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;

        public SearchController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }


        public ActionResult Index(string query)
        {
            var ApplicationDbContext = _context;
            SearchVM search = new SearchVM();

            search.BlogList = _context.Blogs.ToList();
            search.PostList = _context.Posts.Include(p=>p.Blog).ToList();
            search.TagList = _context.Tags.Include(t => t.Post).ToList();

            ViewBag.Query = query;
            TempData["searchpath"] = "search";
            TempData["query"] = query;
            if (!String.IsNullOrEmpty(query))
            {
                search.BlogList = search.BlogList.Where(b => b.Title.ToUpper().Contains(query.ToUpper())).ToList();
                search.PostList = search.PostList.Where(p => p.Title.ToUpper().Contains(query.ToUpper())).ToList();
                search.TagList = search.TagList.Where(t => t.Name.ToUpper().Contains(query.ToUpper())).ToList();
                return View(search);
            }
            else
            { 
                return Problem("The query string was empty!"); 
            }


        }

        public ActionResult ViewBlog(int? blogId, string query)
        {
            SearchVM search = new SearchVM();

            if (blogId != null)
            {
                Blog blog = _context.Blogs.Find(blogId);
                ViewBag.Blog = blog;
                search.PostList = new List<Post>();

               Post postWithTheLatestDate = _context.Posts.Where(p => p.BlogId == blog.Id).OrderByDescending(p => p.Created).FirstOrDefault();
               var PostList = _context.Posts.Where(p => p.BlogId == blog.Id).OrderByDescending(p => p.Created).AsEnumerable().GroupBy(p =>p.Created).Select(g=>g.First());

                foreach (var post in PostList)
                {
                    if(post.Created.ToString("MM").Equals(postWithTheLatestDate.Created.ToString("MM")))
                    { 
                        search.PostList.Add(post); 
                    }
                    
                }

                return View(search.PostList);
            }
            else
            {
                return Problem("Could not retrieve the posts with specific dates");
            }
        }

        public ActionResult ViewPost(int? postId)
        {
            SearchVM search = new SearchVM();

            if (postId != null)
            {
                Post post = _context.Posts.Find(postId);
                Blog blog = _context.Blogs.Find(post.BlogId);
                ViewBag.Blog = blog;
                search.PostList = new List<Post>();
                search.PostList = _context.Posts.
                                     Where(p => p.BlogId == blog.Id)
                                    .ToList();

                search.PostList = search.PostList.Where(p => p.Created.ToString("MM").Equals(post.Created.ToString("MM"))).ToList();

                return View(search.PostList);
            }
            else
            {
                return Problem("Could not retrieve the posts with specific dates");
            }
        }

        public ActionResult ViewPostById(int? postId)
        {
            return View();
        }


    }
}

BlogBravo/Views/Search/Index.cshtml
@model BlogBravo.Models.SearchVM

@{
    ViewData["Title"] = "Index";
}

<div class="row mt-3">
    <h1 id="search-header" class="bg-dark text-white mb-5" style="width:fit-content;">Search Results for Blogs containing:</h1><h1 class="bg-dark text-white mb-5"> &nbsp;@TempData["query"]</h1>
</div>
<div>
    <div class="container btn-group btn-group-lg" role="group">
        <button id="blogs-btn" type="button" class="btn btn-outline-dark active" style="border:solid black; border-radius:0px; border-top-right-radius:20px;">Blogs</button>
        <button id="posts-btn" type="button" class="btn btn-outline-dark" style="border:solid black; border-radius:0px; border-top-right-radius:20px;">Posts</button>
        <button id="tags-btn" type="button" class="btn btn-outline-dark" style="border:solid black; border-radius:0px; border-top-right-radius:20px;">Tags</button>
    </div>
    <div class="container mt-2" id="load-partial-view"></div>
</div>

@*------------------------------------------Blog Search View--------------------------------*@
<div id="blog-view">
    @if (Model.BlogList.Count != 0)
    {
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>
                        Title
                    </th>
                    <th>
                        Body
                    </th>
                    <th>
                        Created
                    </th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.BlogList)
                {
                    <tr>
                        <td>
                            <form name="blog-view-form" method="get" asp-controller="Search" asp-action="ViewBlog">
                                <input name="blogId" value="@item.Id" hidden />
                                <input name="query" value="@ViewBag.Query" hidden />
                                <button class="btn btn-info" onclick="blog-view-form.submit()">@Html.DisplayFor(modelItem => item.Title)</button>
                            </form>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Body)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Created)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <h5 class="text-info"> Search Rendered no Matches</h5>
    }

    <div id="blog-view-page" hidden></div>
</div>

@*------------------------------------------Post Search View--------------------------------*@
<div id="post-view" hidden>
    @if (Model.PostList.Count != 0)
    {
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>
                        Post Title
                    </th>
                    <th>
                        Blog Title
                    </th>
                    <th>
                        Body
                    </th>
                    <th>
                        Created
                    </th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.PostList)
                {
                    string date = item.Created.ToString("yyyy-MM-dd");
                    string postBody = "";

                    if (item.Body.Length < 100)
                    {
                        postBody = item.Body.Substring(0, item.Body.Length);
                    }
                    else
                    {
                        postBody = item.Body.Substring(0, 100) + " ...";
                    }

                    <tr>
                        <td>
                            <form name="post-view-form" method="post" asp-area="" asp-controller="Post" asp-action="Details">
                                <input name="postId" value="@item.Id" hidden />
                                <input id="@item.Id" name="referer" value="@item.Id" hidden />
                                <button class="btn btn-info" onclick="blog-view-form.submit()">@Html.DisplayFor(modelItem => item.Title)</button>
                            </form>
                        </td>
                        <td>
                            <form name="blog-view-form" method="get" asp-controller="Search" asp-action="ViewBlog">
                                <input name="blogId" value="@item.Blog.Id" hidden />
                                <input name="query" value="@ViewBag.Query" hidden />
                                <button class="btn btn-info" onclick="blog-view-form.submit()">@Html.DisplayFor(modelItem => item.Blog.Title)</button>
                            </form>
                        </td>
                        <td>
                            @postBody
                        </td>
                        <td>
                            @date
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <h5 class="text-info"> Search Rendered no Matches</h5>
    }
</div>

@*------------------------------------------Tag Search View--------------------------------*@
<div id="tag-view" hidden>
    @if (Model.TagList.Count != 0)
    {
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>Post Name</th>
                    <th>Blog Name</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.TagList)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        <table>
                            @foreach (var post in item.Post)
                            {
                                <tr>
                                    <td>
                                        <form name="tag-post-view-form" method="post" asp-area="" asp-controller="Post" asp-action="Details">
                                            <input name="postId" value="@post.Id" hidden />
                                            <input name="referer" value="@post.Id" hidden />
                                            <button class="btn btn-info" onclick="blog-view-form.submit()">@post.Title</button>
                                        </form>
                                    </td>
                                </tr>
                            }
                        </table>
                    </td>
                    <td>
                        <table>
                            @foreach (var post in item.Post)
                            {
                                <tr>
                                    <td>
                                        
                                        <form name="blog-view-form" method="get" asp-controller="Search" asp-action="ViewBlog">
                                            <input name="blogId" value="@post.BlogId" hidden />
                                            <input name="query" value="@ViewBag.Query" hidden />
                                            <button class="btn btn-info" onclick="blog-view-form.submit()">@post.Blog.Title</button>
                                        </form>
                                    </td>
                                </tr>
                            }
                        </table>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <h5 class="text-info">Search Rendered no Matches</h5>
    }
</div>


<script>
    document.querySelector("#blogs-btn").addEventListener('click', function () {
        $("#blog-view").prop("hidden", false);
        $("#blogs-btn").addClass("active");
        $("#post-view").prop("hidden", true);
        $("#posts-btn").removeClass("active");
        $("#tag-view").prop("hidden", true);
        $("#tags-btn").removeClass("active");
        $("#search-header").text("");
        $("#search-header").text("Search Results for Blogs containing: ");
    });

    document.querySelector("#posts-btn").addEventListener('click', function () {
        $("#blog-view").prop("hidden", true);
        $("#blogs-btn").removeClass("active");
        $("#post-view").prop("hidden", false);
        $("#posts-btn").addClass("active");
        $("#tag-view").prop("hidden", true);
        $("#tags-btn").removeClass("active");
        $("#search-header").text("");
        $("#search-header").text("Search Results for Posts containing:  ");
    });

    document.querySelector("#tags-btn").addEventListener('click', function () {
        $("#blog-view").prop("hidden", true);
        $("#blogs-btn").removeClass("active");
        $("#post-view").prop("hidden", true);
        $("#posts-btn").removeClass("active");
        $("#tag-view").prop("hidden", false);
        $("#tags-btn").addClass("active");
        $("#search-header").text("");
        $("#search-header").text("Search Results for Posts containing Tag:  ");
    });

    window.onload = function () {
        $("#post-view form").children("input[name='referer']").each(function () {
            $(this).val(document.referrer);
            $("#search-header").text("");
            $("#search-header").text("Search Results for Blogs containing: ");
        });

        $("#tag-view form").children("input[name='referer']").each(function () {
            $(this).val(document.referrer);
            sessionStorage.setItem('returnPath', window.location.href);
        });
    };


</script>

BlogBravo/Views/Search/ViewBlog.cshtml
@model IEnumerable<BlogBravo.Models.Post>

@{
    ViewData["Title"] = "View Post";
}

<h1 class="bg-dark text-white mb-3 rounded" style="width:fit-content">@ViewBag.Blog.Title</h1>


<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Body)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Created)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            string date = item.Created.ToString("yyyy-MM-dd");
            string postBody = "";

            if (item.Body.Length < 100)
            {
                postBody = item.Body.Substring(0, item.Body.Length);
            }
            else
            {
                postBody = item.Body.Substring(0, 100) + " ...";
            }

            <tr>
                <td>
                    <form name="post-view-form" method="post" asp-area="" asp-controller="Post" asp-action="Details">
                        <input name="postId" value="@item.Id" hidden />
                        <button class="btn btn-info" onclick="blog-view-form.submit()">@Html.DisplayFor(modelItem => item.Title)</button>
                    </form>
                </td>
                <td>
                    @postBody
                </td>
                <td>
                    @date
                </td>
            </tr>
        }
    </tbody>
</table>

<a href="##" onClick="history.go(-1); return false;" class="btn btn-outline-dark float-right my-5">Return to Search Result</a>

BlogBravo/Views/Search/ViewPost.cshtml
@model IEnumerable<BlogBravo.Models.Post>

@{
    ViewData["Title"] = "View Post";
}

<h1 class="bg-dark text-white mb-3 rounded" style="width:fit-content">@ViewBag.Blog.Title</h1>


<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Body)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Created)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            string date = item.Created.ToString("yyyy-MM-dd");
            string postBody = "";

            if (item.Body.Length < 100)
            {
                postBody = item.Body.Substring(0, item.Body.Length);
            }
            else
            {
                postBody = item.Body.Substring(0, 100) + " ...";
            }

            <tr>
                <td>
                    <form name="post-view-form" method="post" asp-area="" asp-controller="Post" asp-action="Details">
                        <input name="postId" value="@item.Id" hidden />
                        <button class="btn btn-info" onclick="blog-view-form.submit()">@Html.DisplayFor(modelItem => item.Title)</button>
                    </form>
                </td>
                <td>
                    @postBody
                </td>
                <td>
                    @date
                </td>
            </tr>
        }
    </tbody>
</table>